keys:
  - &admin_yubikey1 age1yubikey1qvy5y8kxqc63y7fk0tfv43u499a8z8q332ff087lythry9cc6hdxxkznc6t
  - &host_x1g13 age12g85cuvg4kjfr79lqf5fx2k0d82tchrgv88xgkt7ukk2cfcsw98s2rjyat
creation_rules:
  - path_regex: ^secrets/common/[^/]+\.ya?ml$
    key_groups:
      - age:
          - *admin_yubikey1
          - *host_x1g13
  - path_regex: ^secrets/hosts/x1g13/[^/]+\.ya?ml$
    key_groups:
      - age:
          - *admin_yubikey1
          - *host_x1g13
